<?php

namespace Database\Seeders;

use App\Models\AkunLevel3;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AkunLevel3Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        AkunLevel3::insert([
            [
                "id" => "111",
                "parent_id" => "11",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "0",
                "kode_akun" => "1.1.01.00",
                "nama_akun" => "Kas",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "112",
                "parent_id" => "11",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "0",
                "kode_akun" => "1.1.02.00",
                "nama_akun" => "Kas Setara Kas",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "113",
                "parent_id" => "11",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "3",
                "lev4" => "0",
                "kode_akun" => "1.1.03.00",
                "nama_akun" => "Piutang",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "114",
                "parent_id" => "11",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "4",
                "lev4" => "0",
                "kode_akun" => "1.1.04.00",
                "nama_akun" => "Cadangan Kerugian Piutang",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "115",
                "parent_id" => "11",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "5",
                "lev4" => "0",
                "kode_akun" => "1.1.05.00",
                "nama_akun" => "Rekening antar Kantor ",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "116",
                "parent_id" => "11",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "6",
                "lev4" => "0",
                "kode_akun" => "1.1.06.00",
                "nama_akun" => "Investasi",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "121",
                "parent_id" => "12",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "0",
                "kode_akun" => "1.2.01.00",
                "nama_akun" => "Aktiva Tetap dan Inventaris",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "122",
                "parent_id" => "12",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "2",
                "lev4" => "0",
                "kode_akun" => "1.2.02.00",
                "nama_akun" => "Akumulasi Penyusutan Aktiva Tetap dan Inventaris",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "123",
                "parent_id" => "12",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "3",
                "lev4" => "0",
                "kode_akun" => "1.2.03.00",
                "nama_akun" => "Aset Tak Berwujud",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "124",
                "parent_id" => "12",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "4",
                "lev4" => "0",
                "kode_akun" => "1.2.04.00",
                "nama_akun" => "Akumulasi Amortisasi Aset Tak Berwujud",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "125",
                "parent_id" => "12",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "5",
                "lev4" => "0",
                "kode_akun" => "1.2.05.00",
                "nama_akun" => "Konstruksi Dalam Pengerjaan",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "131",
                "parent_id" => "13",
                "lev1" => "1",
                "lev2" => "3",
                "lev3" => "1",
                "lev4" => "0",
                "kode_akun" => "1.3.01.00",
                "nama_akun" => "Aset Lain-lain",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "211",
                "parent_id" => "21",
                "lev1" => "2",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "0",
                "kode_akun" => "2.1.01.00",
                "nama_akun" => "Utang Dividen",
                "jenis_mutasi" => "kredit",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "212",
                "parent_id" => "21",
                "lev1" => "2",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "0",
                "kode_akun" => "2.1.02.00",
                "nama_akun" => "Utang Biaya Operasional",
                "jenis_mutasi" => "kredit",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "213",
                "parent_id" => "21",
                "lev1" => "2",
                "lev2" => "1",
                "lev3" => "3",
                "lev4" => "0",
                "kode_akun" => "2.1.03.00",
                "nama_akun" => "Utang Pajak",
                "jenis_mutasi" => "kredit",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "214",
                "parent_id" => "21",
                "lev1" => "2",
                "lev2" => "1",
                "lev3" => "4",
                "lev4" => "0",
                "kode_akun" => "2.1.04.00",
                "nama_akun" => "Utang Jangka Pendek Lainnya",
                "jenis_mutasi" => "kredit",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "221",
                "parent_id" => "22",
                "lev1" => "2",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "0",
                "kode_akun" => "2.2.01.00",
                "nama_akun" => "Utang Jangka Panjang",
                "jenis_mutasi" => "kredit",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "311",
                "parent_id" => "31",
                "lev1" => "3",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "0",
                "kode_akun" => "3.1.01.00",
                "nama_akun" => "Modal Disetor",
                "jenis_mutasi" => "kredit",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "312",
                "parent_id" => "31",
                "lev1" => "3",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "0",
                "kode_akun" => "3.1.02.00",
                "nama_akun" => "Modal Lain-lain",
                "jenis_mutasi" => "kredit",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "321",
                "parent_id" => "32",
                "lev1" => "3",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "0",
                "kode_akun" => "3.2.01.00",
                "nama_akun" => "Laba Ditahan",
                "jenis_mutasi" => "kredit",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "322",
                "parent_id" => "32",
                "lev1" => "3",
                "lev2" => "2",
                "lev3" => "2",
                "lev4" => "0",
                "kode_akun" => "3.2.02.00",
                "nama_akun" => "Laba Rugi Berjalan",
                "jenis_mutasi" => "kredit",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "411",
                "parent_id" => "41",
                "lev1" => "4",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "0",
                "kode_akun" => "4.1.01.00",
                "nama_akun" => "Pendapatan Usaha Utama",
                "jenis_mutasi" => "kredit",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "412",
                "parent_id" => "41",
                "lev1" => "4",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "0",
                "kode_akun" => "4.1.02.00",
                "nama_akun" => "Pendapatan Usaha Lain",
                "jenis_mutasi" => "kredit",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "413",
                "parent_id" => "41",
                "lev1" => "4",
                "lev2" => "1",
                "lev3" => "3",
                "lev4" => "0",
                "kode_akun" => "4.1.03.00",
                "nama_akun" => "Pendapatan Usaha Lain Lainnya",
                "jenis_mutasi" => "kredit",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "421",
                "parent_id" => "42",
                "lev1" => "4",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "0",
                "kode_akun" => "4.2.01.00",
                "nama_akun" => "Pendapatan Non Usaha",
                "jenis_mutasi" => "kredit",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "431",
                "parent_id" => "43",
                "lev1" => "4",
                "lev2" => "3",
                "lev3" => "1",
                "lev4" => "0",
                "kode_akun" => "4.3.01.00",
                "nama_akun" => "Pendapatan Luar biasa",
                "jenis_mutasi" => "kredit",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "511",
                "parent_id" => "51",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "0",
                "kode_akun" => "5.1.01.00",
                "nama_akun" => "Beban Gaji dan Honor",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "512",
                "parent_id" => "51",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "0",
                "kode_akun" => "5.1.02.00",
                "nama_akun" => "Beban Tunjangan dan Bonus",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "513",
                "parent_id" => "51",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "3",
                "lev4" => "0",
                "kode_akun" => "5.1.03.00",
                "nama_akun" => "Beban ATK dan Umum",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "514",
                "parent_id" => "51",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "4",
                "lev4" => "0",
                "kode_akun" => "5.1.04.00",
                "nama_akun" => "Beban Rapat",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "515",
                "parent_id" => "51",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "5",
                "lev4" => "0",
                "kode_akun" => "5.1.05.00",
                "nama_akun" => "Transportasi dan Perjalanan Dinas",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "516",
                "parent_id" => "51",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "6",
                "lev4" => "0",
                "kode_akun" => "5.1.06.00",
                "nama_akun" => "Beban Penyisihan Cadangan",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "517",
                "parent_id" => "51",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "7",
                "lev4" => "0",
                "kode_akun" => "5.1.07.00",
                "nama_akun" => "Beban Penyusutan dan Amortisasi",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "518",
                "parent_id" => "51",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "8",
                "lev4" => "0",
                "kode_akun" => "5.1.08.00",
                "nama_akun" => "Beban Usaha Lainnya",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "519",
                "parent_id" => "51",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "9",
                "lev4" => "0",
                "kode_akun" => "5.1.09.00",
                "nama_akun" => "Beban Bunga Utang",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "521",
                "parent_id" => "52",
                "lev1" => "5",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "0",
                "kode_akun" => "5.2.01.00",
                "nama_akun" => "Beban Pemasaran",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "531",
                "parent_id" => "53",
                "lev1" => "5",
                "lev2" => "3",
                "lev3" => "1",
                "lev4" => "0",
                "kode_akun" => "5.3.01.00",
                "nama_akun" => "Beban Pajak, Bunga dan Administrasi Bank",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "532",
                "parent_id" => "53",
                "lev1" => "5",
                "lev2" => "3",
                "lev3" => "2",
                "lev4" => "0",
                "kode_akun" => "5.3.02.00",
                "nama_akun" => "Beban Penghapusan Aset Tetap",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "533",
                "parent_id" => "53",
                "lev1" => "5",
                "lev2" => "3",
                "lev3" => "3",
                "lev4" => "0",
                "kode_akun" => "5.3.03.00",
                "nama_akun" => "Beban Non Usaha Lainnya",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => "541",
                "parent_id" => "54",
                "lev1" => "5",
                "lev2" => "4",
                "lev3" => "1",
                "lev4" => "0",
                "kode_akun" => "5.4.01.00",
                "nama_akun" => "Beban PPh",
                "jenis_mutasi" => "debet",
                "created_at" => null,
                "updated_at" => null
            ],
        ]);
    }
}
