<?php

namespace Database\Seeders;

use App\Models\Rekening;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RekeningSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Rekening::insert([
            [
                "id" => "1",
                "parent_id" => "111",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "1",
                "kode_akun" => "1.1.01.01",
                "nama_akun" => "Kas Tunai",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "2",
                "parent_id" => "111",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "2",
                "kode_akun" => "1.1.01.02",
                "nama_akun" => "Kas Kas Kecil",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "3",
                "parent_id" => "111",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "3",
                "kode_akun" => "1.1.01.03",
                "nama_akun" => "Kas di Bank BRI",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "4",
                "parent_id" => "111",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "4",
                "kode_akun" => "1.1.01.04",
                "nama_akun" => "Kas di Bank Mandiri",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "5",
                "parent_id" => "112",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "1",
                "kode_akun" => "1.1.02.01",
                "nama_akun" => "Deposito",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "6",
                "parent_id" => "112",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "2",
                "kode_akun" => "1.1.02.02",
                "nama_akun" => "Obligasi",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "7",
                "parent_id" => "112",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "3",
                "kode_akun" => "1.1.02.03",
                "nama_akun" => "Saham",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "8",
                "parent_id" => "113",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "3",
                "lev4" => "1",
                "kode_akun" => "1.1.03.01",
                "nama_akun" => "Piutang Usaha",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "9",
                "parent_id" => "113",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "3",
                "lev4" => "2",
                "kode_akun" => "1.1.03.02",
                "nama_akun" => "Piutang Karyawan",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "10",
                "parent_id" => "113",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "3",
                "lev4" => "3",
                "kode_akun" => "1.1.03.03",
                "nama_akun" => "Piutang Lain",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "11",
                "parent_id" => "114",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "4",
                "lev4" => "1",
                "kode_akun" => "1.1.04.01",
                "nama_akun" => "Cadangan Kerugian Piutang",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "12",
                "parent_id" => "115",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "5",
                "lev4" => "1",
                "kode_akun" => "1.1.05.01",
                "nama_akun" => "Persediaan",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "13",
                "parent_id" => "116",
                "lev1" => "1",
                "lev2" => "1",
                "lev3" => "6",
                "lev4" => "1",
                "kode_akun" => "1.1.06.01",
                "nama_akun" => "Rekening Antar Kantor",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "14",
                "parent_id" => "121",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "1",
                "kode_akun" => "1.2.01.01",
                "nama_akun" => "Tanah",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "15",
                "parent_id" => "121",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "2",
                "kode_akun" => "1.2.01.02",
                "nama_akun" => "Gedung & Bangunan",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "16",
                "parent_id" => "121",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "3",
                "kode_akun" => "1.2.01.03",
                "nama_akun" => "Kendaraan dan Mesin",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "17",
                "parent_id" => "121",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "4",
                "kode_akun" => "1.2.01.04",
                "nama_akun" => "Inventaris\/Peralatan",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "18",
                "parent_id" => "122",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "2",
                "lev4" => "1",
                "kode_akun" => "1.2.02.01",
                "nama_akun" => "Akumulasi penyusutan Gedung dan Bangunan",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "19",
                "parent_id" => "122",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "2",
                "lev4" => "2",
                "kode_akun" => "1.2.02.02",
                "nama_akun" => "Akumulasi penyusutan Kendaraan dan Mesin",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "20",
                "parent_id" => "122",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "2",
                "lev4" => "3",
                "kode_akun" => "1.2.02.03",
                "nama_akun" => "Akumulasi penyusutan Inventaris\/Peralatan",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "21",
                "parent_id" => "123",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "3",
                "lev4" => "1",
                "kode_akun" => "1.2.03.01",
                "nama_akun" => "Perijinan",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "22",
                "parent_id" => "123",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "3",
                "lev4" => "2",
                "kode_akun" => "1.2.03.02",
                "nama_akun" => "Lisensi",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "23",
                "parent_id" => "123",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "3",
                "lev4" => "3",
                "kode_akun" => "1.2.03.03",
                "nama_akun" => "Sewa dibayar dimuka",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "24",
                "parent_id" => "124",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "4",
                "lev4" => "1",
                "kode_akun" => "1.2.04.01",
                "nama_akun" => "Akumulasi Amortisasi Biaya Perijinan",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "25",
                "parent_id" => "124",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "4",
                "lev4" => "2",
                "kode_akun" => "1.2.04.02",
                "nama_akun" => "Akumulasi Amortisasi Lisensi",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "26",
                "parent_id" => "124",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "4",
                "lev4" => "3",
                "kode_akun" => "1.2.04.03",
                "nama_akun" => "Akumulasi Amortisasi Sewa dibayar dimuka",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "27",
                "parent_id" => "125",
                "lev1" => "1",
                "lev2" => "2",
                "lev3" => "5",
                "lev4" => "1",
                "kode_akun" => "1.2.05.01",
                "nama_akun" => "Konstruksi Dalam Pengerjaan dan Uang Muka",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "28",
                "parent_id" => "131",
                "lev1" => "1",
                "lev2" => "3",
                "lev3" => "1",
                "lev4" => "1",
                "kode_akun" => "1.3.01.01",
                "nama_akun" => "Aset Lain-lain",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "29",
                "parent_id" => "211",
                "lev1" => "2",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "1",
                "kode_akun" => "2.1.01.01",
                "nama_akun" => "Utang Dividen Bumdesma",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "30",
                "parent_id" => "211",
                "lev1" => "2",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "2",
                "kode_akun" => "2.1.01.02",
                "nama_akun" => "Utang Dividen Penyerta Modal",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "31",
                "parent_id" => "211",
                "lev1" => "2",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "3",
                "kode_akun" => "2.1.01.03",
                "nama_akun" => "Bantuan Sosial",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "32",
                "parent_id" => "212",
                "lev1" => "2",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "1",
                "kode_akun" => "2.1.02.01",
                "nama_akun" => "Utang Operasional",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "33",
                "parent_id" => "212",
                "lev1" => "2",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "2",
                "kode_akun" => "2.1.02.02",
                "nama_akun" => "Utang FEE Kolektor",
                "jenis_mutasi" => "Kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "34",
                "parent_id" => "212",
                "lev1" => "2",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "3",
                "kode_akun" => "2.1.02.03",
                "nama_akun" => "Utang Bonus",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "35",
                "parent_id" => "213",
                "lev1" => "2",
                "lev2" => "1",
                "lev3" => "3",
                "lev4" => "1",
                "kode_akun" => "2.1.03.01",
                "nama_akun" => "Utang Pajak",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "36",
                "parent_id" => "214",
                "lev1" => "2",
                "lev2" => "1",
                "lev3" => "4",
                "lev4" => "1",
                "kode_akun" => "2.1.04.01",
                "nama_akun" => "Utang Pihak Ke-3",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "37",
                "parent_id" => "214",
                "lev1" => "2",
                "lev2" => "1",
                "lev3" => "4",
                "lev4" => "2",
                "kode_akun" => "2.1.04.02",
                "nama_akun" => "Utang jangka pendek lainya",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "38",
                "parent_id" => "221",
                "lev1" => "2",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "1",
                "kode_akun" => "2.2.01.01",
                "nama_akun" => "Utang Bank",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "39",
                "parent_id" => "221",
                "lev1" => "2",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "2",
                "kode_akun" => "2.2.01.02",
                "nama_akun" => "Utang Non Bank",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "40",
                "parent_id" => "222",
                "lev1" => "2",
                "lev2" => "2",
                "lev3" => "2",
                "lev4" => "1",
                "kode_akun" => "2.2.02.01",
                "nama_akun" => "Utang Jangka Panjang Lainnya",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "41",
                "parent_id" => "311",
                "lev1" => "3",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "1",
                "kode_akun" => "3.1.01.01",
                "nama_akun" => "Modal Bumdesma",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "42",
                "parent_id" => "311",
                "lev1" => "3",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "2",
                "kode_akun" => "3.1.01.02",
                "nama_akun" => "Modal Penyertaan",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "43",
                "parent_id" => "312",
                "lev1" => "3",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "1",
                "kode_akun" => "3.1.02.01",
                "nama_akun" => "Modal Lain-lain",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "44",
                "parent_id" => "321",
                "lev1" => "3",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "1",
                "kode_akun" => "3.2.01.01",
                "nama_akun" => "Laba Ditahan s\/d Tahun lalu",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "45",
                "parent_id" => "321",
                "lev1" => "3",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "2",
                "kode_akun" => "3.2.01.02",
                "nama_akun" => "Laba Tahun lalu belum dibagi",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "46",
                "parent_id" => "322",
                "lev1" => "3",
                "lev2" => "2",
                "lev3" => "2",
                "lev4" => "1",
                "kode_akun" => "3.2.02.01",
                "nama_akun" => "Laba\/Rugi Tahun Berjalan",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "47",
                "parent_id" => "411",
                "lev1" => "4",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "1",
                "kode_akun" => "4.1.01.01",
                "nama_akun" => "Jasa Internet",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "48",
                "parent_id" => "411",
                "lev1" => "4",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "2",
                "kode_akun" => "4.1.01.02",
                "nama_akun" => "Pemasangan Baru",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "49",
                "parent_id" => "411",
                "lev1" => "4",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "3",
                "kode_akun" => "4.1.01.03",
                "nama_akun" => "Penambahan Kabel",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "50",
                "parent_id" => "411",
                "lev1" => "4",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "1",
                "kode_akun" => "4.1.02.01",
                "nama_akun" => "Denda Pemutusan",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "51",
                "parent_id" => "413",
                "lev1" => "4",
                "lev2" => "1",
                "lev3" => "3",
                "lev4" => "1",
                "kode_akun" => "4.1.03.01",
                "nama_akun" => "Pendapatan lain",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "52",
                "parent_id" => "421",
                "lev1" => "4",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "1",
                "kode_akun" => "4.2.01.01",
                "nama_akun" => "Pendapatan Bunga Bank",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "53",
                "parent_id" => "421",
                "lev1" => "4",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "2",
                "kode_akun" => "4.2.01.02",
                "nama_akun" => "Pendapatan Hadiah",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "54",
                "parent_id" => "421",
                "lev1" => "4",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "3",
                "kode_akun" => "4.2.01.03",
                "nama_akun" => "Pendapatan Hibah",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "55",
                "parent_id" => "421",
                "lev1" => "4",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "4",
                "kode_akun" => "4.2.01.04",
                "nama_akun" => "Pertambahan Nilai Penjualan Aset",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "56",
                "parent_id" => "421",
                "lev1" => "4",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "5",
                "kode_akun" => "4.2.01.05",
                "nama_akun" => "Pendapatan Non Usaha Lainnya",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "57",
                "parent_id" => "431",
                "lev1" => "4",
                "lev2" => "3",
                "lev3" => "1",
                "lev4" => "1",
                "kode_akun" => "4.3.01.01",
                "nama_akun" => "Pendapatan revaluasi Aset",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "58",
                "parent_id" => "431",
                "lev1" => "4",
                "lev2" => "3",
                "lev3" => "1",
                "lev4" => "2",
                "kode_akun" => "4.3.01.02",
                "nama_akun" => "Pendapatan revaluasi Saham",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "59",
                "parent_id" => "431",
                "lev1" => "4",
                "lev2" => "3",
                "lev3" => "1",
                "lev4" => "3",
                "kode_akun" => "4.3.01.03",
                "nama_akun" => "Pendapatan Luar Biasa Lainnya",
                "jenis_mutasi" => "kredit",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "60",
                "parent_id" => "511",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "1",
                "kode_akun" => "5.1.01.01",
                "nama_akun" => "Gaji Pegawai",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "61",
                "parent_id" => "511",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "2",
                "kode_akun" => "5.1.01.02",
                "nama_akun" => "Gaji Teknisi",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "62",
                "parent_id" => "511",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "3",
                "kode_akun" => "5.1.01.03",
                "nama_akun" => "Honor Pembina",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "63",
                "parent_id" => "511",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "1",
                "lev4" => "4",
                "kode_akun" => "5.1.01.04",
                "nama_akun" => "Honor Pengawas",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "64",
                "parent_id" => "512",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "1",
                "kode_akun" => "5.1.02.01",
                "nama_akun" => "Beban Tunjangan Pegawai",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "65",
                "parent_id" => "512",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "2",
                "kode_akun" => "5.1.02.02",
                "nama_akun" => "Beban Lembur Pegawai",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "66",
                "parent_id" => "512",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "3",
                "kode_akun" => "5.1.02.03",
                "nama_akun" => "Beban Transportasi",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "67",
                "parent_id" => "512",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "4",
                "kode_akun" => "5.1.02.04",
                "nama_akun" => "Beban SPPD",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "68",
                "parent_id" => "512",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "2",
                "lev4" => "5",
                "kode_akun" => "5.1.02.05",
                "nama_akun" => "Beban Bonus Prestasi Kerja",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "69",
                "parent_id" => "513",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "3",
                "lev4" => "1",
                "kode_akun" => "5.1.03.01",
                "nama_akun" => "Beban Administrasi dan Umum",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "70",
                "parent_id" => "515",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "5",
                "lev4" => "1",
                "kode_akun" => "5.1.05.01",
                "nama_akun" => "Beban Pasang Baru",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "71",
                "parent_id" => "515",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "5",
                "lev4" => "2",
                "kode_akun" => "5.1.05.02",
                "nama_akun" => "Beban Pemeliharaan & Perbaikan Aset",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "72",
                "parent_id" => "516",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "6",
                "lev4" => "1",
                "kode_akun" => "5.1.06.01",
                "nama_akun" => "Beban Rapat",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "73",
                "parent_id" => "516",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "6",
                "lev4" => "2",
                "kode_akun" => "5.1.06.02",
                "nama_akun" => "Beban Peningkatan Kapasitas",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "74",
                "parent_id" => "517",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "7",
                "lev4" => "1",
                "kode_akun" => "5.1.07.01",
                "nama_akun" => "Beban Penyisihan Kerugian Piutang",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "75",
                "parent_id" => "518",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "8",
                "lev4" => "1",
                "kode_akun" => "5.1.08.01",
                "nama_akun" => "Beban Penyusutan Gedung dan Bangunan",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "76",
                "parent_id" => "518",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "8",
                "lev4" => "2",
                "kode_akun" => "5.1.08.02",
                "nama_akun" => "Beban Penyusutan Kendaraan & Mesin",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "77",
                "parent_id" => "518",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "8",
                "lev4" => "3",
                "kode_akun" => "5.1.08.03",
                "nama_akun" => "Beban Penyusutan Inventaris",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "78",
                "parent_id" => "518",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "8",
                "lev4" => "4",
                "kode_akun" => "5.1.08.04",
                "nama_akun" => "Beban Amortisasi Biaya Perijinan",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "79",
                "parent_id" => "518",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "8",
                "lev4" => "5",
                "kode_akun" => "5.1.08.05",
                "nama_akun" => "Beban Amortisasi Lisensi",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "80",
                "parent_id" => "518",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "8",
                "lev4" => "6",
                "kode_akun" => "5.1.08.06",
                "nama_akun" => "Beban Amortisasi Sewa dibayar dimuka",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "81",
                "parent_id" => "519",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "9",
                "lev4" => "1",
                "kode_akun" => "5.1.09.01",
                "nama_akun" => "Beban Operasional Lain-lain",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "82",
                "parent_id" => "521",
                "lev1" => "5",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "1",
                "kode_akun" => "5.2.01.01",
                "nama_akun" => "Beban Belanja Persediaan Sparepart",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "83",
                "parent_id" => "531",
                "lev1" => "5",
                "lev2" => "3",
                "lev3" => "1",
                "lev4" => "1",
                "kode_akun" => "5.3.01.01",
                "nama_akun" => "Beban Pajak Bank",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "84",
                "parent_id" => "531",
                "lev1" => "5",
                "lev2" => "3",
                "lev3" => "1",
                "lev4" => "2",
                "kode_akun" => "5.3.01.02",
                "nama_akun" => "Beban Administrasi Bank",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "85",
                "parent_id" => "532",
                "lev1" => "5",
                "lev2" => "3",
                "lev3" => "2",
                "lev4" => "1",
                "kode_akun" => "5.3.02.01",
                "nama_akun" => "Beban Penghapusan Aset Tetap dan Inventaris",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "86",
                "parent_id" => "533",
                "lev1" => "5",
                "lev2" => "3",
                "lev3" => "3",
                "lev4" => "1",
                "kode_akun" => "5.3.03.01",
                "nama_akun" => "Beban Non Usaha Lainnya",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "87",
                "parent_id" => "541",
                "lev1" => "5",
                "lev2" => "4",
                "lev3" => "1",
                "lev4" => "1",
                "kode_akun" => "5.4.01.01",
                "nama_akun" => "Taksiran PPh",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "88",
                "parent_id" => "115",
                "lev1" => "1",
                "lev2" => "4",
                "lev3" => "5",
                "lev4" => "2",
                "kode_akun" => "1.1.05.02",
                "nama_akun" => "Perlengkapan",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "89",
                "parent_id" => "518",
                "lev1" => "5",
                "lev2" => "1",
                "lev3" => "8",
                "lev4" => "7",
                "kode_akun" => "5.1.08.07",
                "nama_akun" => "Beban Sewa",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
            [
                "id" => "90",
                "parent_id" => "521",
                "lev1" => "5",
                "lev2" => "2",
                "lev3" => "1",
                "lev4" => "2",
                "kode_akun" => "5.2.01.02",
                "nama_akun" => "Beban Pemasaran Lain",
                "jenis_mutasi" => "debet",
                "created_at" => "2024-12-26 12=>37=>58",
                "updated_at" => "2024-12-26 12=>37=>58"
            ],
        ]);
    }
}
